# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    hev:
                        password: '%users_hev_password%'
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            anonymous: ~

            # @see https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login

            # @see https://symfony.com/doc/current/security.html#logging-out
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }