# @see https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        admin_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        admin:
            anonymous: ~
            provider: admin_db_provider

            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /admin

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }