# @see https://circleci.com/docs/2.0/
version: 2
jobs:
  php:
    working_directory: ~/hev-leinwand-herner-ev-com/php
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - php-v1-dependencies-{{ checksum "composer.lock" }}
            - php-v1-dependencies-

      - run: composer install -n --prefer-dist --no-scripts

      - save_cache:
          paths:
            - ./vendor
          key: php-v1-dependencies-{{ checksum "composer.lock" }}

      - run: composer test
  js:
    working-directory: ~/hev-leinwand-herner-ev-com/php
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - js-v1-dependencies-{{ checksum "package-lock.json" }}
            - js-v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ./node_modules
          key: php-v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm test

workflows:
  version: 2
  backend:
    jobs:
      - php
  frontend:
    jobs:
      - js
