# @see https://circleci.com/docs/2.0/
version: 2
jobs:
  php:
    working_directory: ~/tools-herner-ev-com/php
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - php-dependencies-{{ checksum "composer.lock" }}
            - php-dependencies-

      - run: composer install -n --prefer-dist --no-scripts

      - save_cache:
          paths:
            - ./vendor
          key: php-dependencies-{{ checksum "composer.lock" }}

      - run: php ./bin/phpunit
  js:
    working-directory: ~/tools-herner-ev-com/js
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "package-lock.json" }}
            - js-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ./node_modules
          key: js-dependencies-{{ checksum "package-lock.json" }}

      - run: npm test

workflows:
  version: 2
  backend:
    jobs:
      - php
  frontend:
    jobs:
      - js
